import type { GachaItem } from "./gacha";

// ── C: Common ────────────────────────────────────────────────────────────────
export const DEFAULT_C_ITEMS: GachaItem[] = [
  { id:"c01", rarity:"C", text:"วันนี้เก่งมากแล้วนะ", image:"/Im/sacdsacfasc.png" },
  { id:"c02", rarity:"C", text:"พักผ่อนบ้างนะ เป็นห่วง", image:"/Im/scascfsaf.png" },
  { id:"c03", rarity:"C", text:"เธอยิ้มสวยที่สุดเลยรู้ไหม", image:"/Im/sacdvewvre.png" },
  { id:"c04", rarity:"C", text:"วันนี้ขอให้โลกใจดีกับเธอนะ", image:"/Im/wefwefewf.png" },
  { id:"c05", rarity:"C", text:"ขอบคุณที่พยายามมาอย่างดีในวันนี้", image:"/Im/acadc7.png" },
  { id:"c06", rarity:"C", text:"ถึงใครจะไม่เห็นความตั้งใจของเธอ แต่เราเห็นนะ", image:"/Im/sacdsacfasc.png" },
  { id:"c07", rarity:"C", text:"ยิ้มหน่อยนะคนเก่งของเค้า", image:"/Im/scascfsaf.png" },
  { id:"c08", rarity:"C", text:"ทานข้าวให้อิ่มนะ อย่าปล่อยให้หิว", image:"/Im/sacdvewvre.png" },
  { id:"c09", rarity:"C", text:"เธอคือความสดใสของวันเลยนะ", image:"/Im/wefwefewf.png" },
  { id:"c10", rarity:"C", text:"เหนื่อยไหม? มาให้กอดทีนึง", image:"/Im/acadc7.png" },
  { id:"c11", rarity:"C", text:"วันนี้เธอทำดีที่สุดแล้วจริงๆ", image:"/Im/sacdsacfasc.png" },
  { id:"c12", rarity:"C", text:"ขอให้วันนี้ไม่มีอะไรมาทำให้เธอขุ่นมัวนะ", image:"/Im/scascfsaf.png" },
  { id:"c13", rarity:"C", text:"เก่งที่สุดในโลกเลยคนนี้", image:"/Im/sacdvewvre.png" },
  { id:"c14", rarity:"C", text:"พรุ่งนี้ค่อยเริ่มใหม่นะ วันนี้พักก่อน", image:"/Im/wefwefewf.png" },
  { id:"c15", rarity:"C", text:"เธอเท่ที่สุดตอนที่ตั้งใจทำอะไรสักอย่าง", image:"/Im/acadc7.png" },
  { id:"c16", rarity:"C", text:"อย่าลืมดื่มน้ำเยอะๆ นะ", image:"/Im/sacdsacfasc.png" },
  { id:"c17", rarity:"C", text:"เป็นกำลังใจให้เสมอ อยู่ตรงนี้แหละ", image:"/Im/scascfsaf.png" },
  { id:"c18", rarity:"C", text:"วันนี้เธอผ่านมันมาได้แล้วนะ เย้!", image:"/Im/sacdvewvre.png" },
  { id:"c19", rarity:"C", text:"ไม่ต้องรีบนะ ค่อยๆ เดินไปก็ได้", image:"/Im/wefwefewf.png" },
  { id:"c20", rarity:"C", text:"เชื่อมั่นในตัวเองหน่อย เธอเก่งกว่าที่คิด", image:"/Im/acadc7.png" },
  { id:"c21", rarity:"C", text:"สู้ๆ นะ เค้าเชียร์เธออยู่", image:"/Im/sacdsacfasc.png" },
  { id:"c22", rarity:"C", text:"หายใจเข้าลึกๆ ทุกอย่างจะโอเค", image:"/Im/scascfsaf.png" },
  { id:"c23", rarity:"C", text:"โลกนี้โชคดีที่มีเธออยู่", image:"/Im/sacdvewvre.png" },
  { id:"c24", rarity:"C", text:"วันนี้เหนื่อยหน่อยนะ เดี๋ยวก็ได้พักแล้ว", image:"/Im/wefwefewf.png" },
  { id:"c25", rarity:"C", text:"ยินดีกับความสำเร็จเล็กๆ ของเธอในวันนี้นะ", image:"/Im/acadc7.png" },
  { id:"c26", rarity:"C", text:"เธอเป็นคนเก่งที่น่ารักที่สุดเลย", image:"/Im/sacdsacfasc.png" },
  { id:"c27", rarity:"C", text:"สดใสเข้าไว้นะคนดี", image:"/Im/scascfsaf.png" },
  { id:"c28", rarity:"C", text:"ทำวันนี้ให้เต็มที่ก็พอแล้ว", image:"/Im/sacdvewvre.png" },
  { id:"c29", rarity:"C", text:"อย่าลืมใจดีกับตัวเองบ้างนะ", image:"/Im/wefwefewf.png" },
  { id:"c30", rarity:"C", text:"เธอคือ Best Version ของตัวเองเสมอ", image:"/Im/acadc7.png" },
  { id:"c31", rarity:"C", text:"วันนี้เธอดูดีมากเลยนะ", image:"/Im/sacdsacfasc.png" },
  { id:"c32", rarity:"C", text:"ท้องฟ้าวันนี้สวยนะ แต่เธอน่ารักกว่า", image:"/Im/scascfsaf.png" },
  { id:"c33", rarity:"C", text:"ไปหาของอร่อยๆ กินกันเถอะ", image:"/Im/sacdvewvre.png" },
  { id:"c34", rarity:"C", text:"วันนี้มีเรื่องอะไรทำให้ยิ้มได้บ้างไหม?", image:"/Im/wefwefewf.png" },
  { id:"c35", rarity:"C", text:"เธอทำได้อยู่แล้ว เชื่อใจนะ", image:"/Im/acadc7.png" },
  { id:"c36", rarity:"C", text:"ขอบคุณที่เป็นพลังบวกให้เค้าเสมอ", image:"/Im/sacdsacfasc.png" },
  { id:"c37", rarity:"C", text:"อย่ากดดันตัวเองเกินไปนะ", image:"/Im/scascfsaf.png" },
  { id:"c38", rarity:"C", text:"พักสายตาบ้างนะ ทำงานหนักมาทั้งวันแล้ว", image:"/Im/sacdvewvre.png" },
  { id:"c39", rarity:"C", text:"เธอคือความภูมิใจของเค้านะ", image:"/Im/wefwefewf.png" },
  { id:"c40", rarity:"C", text:"ทุกอย่างมีจังหวะของมัน ไม่ต้องรีบนะ", image:"/Im/acadc7.png" },
];

// ── R: Rare ──────────────────────────────────────────────────────────────────
export const DEFAULT_R_ITEMS: GachaItem[] = [
  { id:"r41", rarity:"R", text:"ขอบคุณที่เลือกเดินข้างกันนะ", image:"/Im/deqdfeqf.png" },
  { id:"r42", rarity:"R", text:"มีเธออยู่ด้วยแล้วโลกน่าอยู่ขึ้นเยอะเลย", image:"/Im/give-love_5680123.png" },
  { id:"r43", rarity:"R", text:"ดีใจจังที่มีเธอเป็นแฟน", image:"/Im/love_2839131.png" },
  { id:"r44", rarity:"R", text:"ไม่ว่าจะเกิดอะไรขึ้น เค้าอยู่ข้างเธอเสมอนะ", image:"/Im/deqdfeqf.png" },
  { id:"r45", rarity:"R", text:"เธอคือ Safe Zone ที่ดีที่สุดของเค้า", image:"/Im/give-love_5680123.png" },
  { id:"r46", rarity:"R", text:"ขอบคุณที่อดทนกับเค้าในวันที่เค้าไม่น่ารัก", image:"/Im/love_2839131.png" },
  { id:"r47", rarity:"R", text:"ทุกวินาทีที่มีเธอ มันมีความหมายมากนะ", image:"/Im/deqdfeqf.png" },
  { id:"r48", rarity:"R", text:"ตกหลุมรักเธอซ้ำๆ ทุกวันเลย", image:"/Im/give-love_5680123.png" },
  { id:"r49", rarity:"R", text:"เธอคือของขวัญที่ดีที่สุดที่เค้าเคยได้รับ", image:"/Im/love_2839131.png" },
  { id:"r50", rarity:"R", text:"ขอบคุณที่เข้ามาทำให้ชีวิตเค้าสมบูรณ์ขึ้น", image:"/Im/deqdfeqf.png" },
  { id:"r51", rarity:"R", text:"อยากตื่นมาเจอเธอแบบนี้ไปทุกวันเลย", image:"/Im/give-love_5680123.png" },
  { id:"r52", rarity:"R", text:"ไม่ว่าใครจะว่ายังไง เธอยังเป็นที่ 1 ของเค้านะ", image:"/Im/love_2839131.png" },
  { id:"r53", rarity:"R", text:"รักนะ... มากกว่าเมื่อวาน และน้อยกว่าพรุ่งนี้", image:"/Im/deqdfeqf.png" },
  { id:"r54", rarity:"R", text:"ขอบคุณที่เป็นความสบายใจให้กันเสมอ", image:"/Im/give-love_5680123.png" },
  { id:"r55", rarity:"R", text:"ชอบเวลาที่เราได้หัวเราะไปด้วยกันจัง", image:"/Im/love_2839131.png" },
  { id:"r56", rarity:"R", text:"เธอคือคนเดียวที่เค้าอยากเล่าทุกอย่างให้ฟัง", image:"/Im/deqdfeqf.png" },
  { id:"r57", rarity:"R", text:"อนาคตของเค้า อยากให้มีเธออยู่ในนั้นด้วยนะ", image:"/Im/give-love_5680123.png" },
  { id:"r58", rarity:"R", text:"ขอบคุณที่รักในแบบที่เค้าเป็น", image:"/Im/love_2839131.png" },
  { id:"r59", rarity:"R", text:"ไม่ว่าจะไปที่ไหน ขอแค่มีเธอไปด้วยก็พอ", image:"/Im/deqdfeqf.png" },
  { id:"r60", rarity:"R", text:"เธอทำให้เค้าอยากเป็นคนที่ดีขึ้นในทุกวัน", image:"/Im/give-love_5680123.png" },
  { id:"r61", rarity:"R", text:"อยู่เป็นความสุขให้กันแบบนี้ไปนานๆ นะ", image:"/Im/love_2839131.png" },
  { id:"r62", rarity:"R", text:"ถึงจะยุ่งแค่ไหน แต่เธอก็สำคัญที่สุดเสมอ", image:"/Im/deqdfeqf.png" },
  { id:"r63", rarity:"R", text:"ขอบคุณที่คอยซัพพอร์ตกันมาตลอด", image:"/Im/give-love_5680123.png" },
  { id:"r64", rarity:"R", text:"เธอคือแรงบันดาลใจในการใช้ชีวิตของเค้าเลย", image:"/Im/love_2839131.png" },
  { id:"r65", rarity:"R", text:"ชอบตัวเองเวลาที่อยู่กับเธอที่สุดเลย", image:"/Im/deqdfeqf.png" },
  { id:"r66", rarity:"R", text:"ขอบคุณที่โลกเหวี่ยงเรามาเจอกัน", image:"/Im/give-love_5680123.png" },
  { id:"r67", rarity:"R", text:"จะวันไหนๆ เค้าก็ยังเลือกเธอนะ", image:"/Im/love_2839131.png" },
  { id:"r68", rarity:"R", text:"เธอคือคนโปรดของเค้าตลอดกาล", image:"/Im/deqdfeqf.png" },
  { id:"r69", rarity:"R", text:"แค่เห็นหน้าเธอ ความเหนื่อยก็หายไปครึ่งนึงแล้ว", image:"/Im/give-love_5680123.png" },
  { id:"r70", rarity:"R", text:"รักในทุกรายละเอียดที่เป็นเธอเลยนะ", image:"/Im/love_2839131.png" },
];

// ── SR: Super Rare ────────────────────────────────────────────────────────────
export const DEFAULT_SR_ITEMS: GachaItem[] = [
  { id:"sr71", rarity:"SR", text:"ในวันที่เธอไม่รักตัวเอง อย่าลืมว่าเค้ารักเธอนะ", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr72", rarity:"SR", text:"ร้องไห้ออกมาเถอะ เค้าจะคอยซับน้ำตาให้เอง", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr73", rarity:"SR", text:"ไม่ต้องเก่งตลอดเวลาก็ได้ อ่อนแอหน้าเค้าได้เสมอ", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr74", rarity:"SR", text:"ถ้าโลกนี้ใจร้ายกับเธอ มาหลบหลังเค้านะ", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr75", rarity:"SR", text:"ขอบคุณที่ผ่านเรื่องยากๆ มาเพื่อมาเจอกัน", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr76", rarity:"SR", text:"เธอไม่ได้สู้ตัวคนเดียวนะ เค้าสู้ไปกับเธอด้วย", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr77", rarity:"SR", text:"ถึงวันนี้จะแย่ แต่เธอยังมีเค้าที่รักเธอที่สุดนะ", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr78", rarity:"SR", text:"เธอไม่ต้องสมบูรณ์แบบหรอก แค่เป็นเธอก็พอแล้ว", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr79", rarity:"SR", text:"ทุกความผิดพลาดคือบทเรียน เราจะเรียนรู้ไปด้วยกัน", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr80", rarity:"SR", text:"เค้าเชื่อในตัวเธอเสมอ ไม่ว่าคนอื่นจะมองยังไง", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr81", rarity:"SR", text:"ขอบคุณที่ยังเข้มแข็งจนถึงวันนี้นะ", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr82", rarity:"SR", text:"พลังของเธออยู่ที่เค้าเสมอนะ มาแบ่งไปได้ตลอด", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr83", rarity:"SR", text:"ไม่ต้องกลัวนะ เค้าจะไม่ปล่อยมือเธอแน่นอน", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr84", rarity:"SR", text:"เธอคือเหตุผลที่ทำให้เค้าอยากตื่นมาในทุกๆ วัน", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr85", rarity:"SR", text:"ต่อให้วันข้างหน้าจะยากแค่ไหน เราจะผ่านมันไปด้วยกัน", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr86", rarity:"SR", text:"เธอมีค่าเกินกว่าจะเสียน้ำตาให้คนที่ไม่เห็นค่านะ", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr87", rarity:"SR", text:"อยากให้เธอรู้ว่าเธอน่ารักที่สุดในสายตาเค้าเสมอ", image:"/Im/teddy-bear_4593749.png" },
  { id:"sr88", rarity:"SR", text:"หัวใจเค้าเป็นของเธอตั้งแต่วันแรก และจะเป็นตลอดไป", image:"/Im/teddy-bear_4841256.png" },
  { id:"sr89", rarity:"SR", text:"ขอบคุณที่เข้ามาเป็นเรื่องราวดีๆ ในชีวิตเค้านะ", image:"/Im/teddy-bear_1746403.png" },
  { id:"sr90", rarity:"SR", text:"รักเธอนะ... รักที่เป็นเธอจริงๆ", image:"/Im/teddy-bear_4593749.png" },
];

// ── SSR: Legendary ────────────────────────────────────────────────────────────
export const DEFAULT_SSR_ITEMS: GachaItem[] = [
  { id:"ssr91",  rarity:"SSR", text:"[คูปอง] นวดไหล่/นวดเท้า 30 นาที\nใช้ได้ทันทีเลย! ไม่มีข้ออ้าง",  image:"/Im/12121212.png" },
  { id:"ssr92",  rarity:"SSR", text:"[คูปอง] ตามใจ 1 วันเต็ม\nจะไปไหน ทำอะไร บอกเลย!",              image:"/Im/12121212.png" },
  { id:"ssr93",  rarity:"SSR", text:"[คูปอง] บุฟเฟต์ 1 มื้อ\nเค้าเป็นเจ้ามือเอง ไปได้เลย!",         image:"/Im/12121212.png" },
  { id:"ssr94",  rarity:"SSR", text:"[คูปอง] ห้ามโกรธ 1 ชั่วโมง\nไม่ว่าเค้าจะกวนแค่ไหน",            image:"/Im/12121212.png" },
  { id:"ssr95",  rarity:"SSR", text:"[คูปอง] พาไปเที่ยวที่ไหนก็ได้ 1 ทริป\nเลือกได้เลยเลย!",        image:"/Im/12121212.png" },
  { id:"ssr96",  rarity:"SSR", text:"[คูปอง] กอดแน่นๆ จนกว่าจะหายเหนื่อย\nไม่มีกำหนดเวลา",          image:"/Im/12121212.png" },
  { id:"ssr97",  rarity:"SSR", text:"[คูปอง] ของหวาน 1 อย่าง\nเดี๋ยวสั่ง Grab ไปให้เองเลย!",        image:"/Im/12121212.png" },
  { id:"ssr98",  rarity:"SSR", text:"[คูปอง] ดูหนังตามใจเธอ 1 เรื่อง\nห้ามบ่น รับรอง!",             image:"/Im/12121212.png" },
  { id:"ssr99",  rarity:"SSR", text:"[คูปอง] ไม่ต้องล้างจาน/ทำงานบ้าน 1 วัน\nเค้าทำเองทุกอย่าง",   image:"/Im/12121212.png" },
  { id:"ssr100", rarity:"SSR", text:"[Super Secret] บอกรักแบบตะโกน 1 ครั้ง!\nรับได้เลย ตอนนี้เลย!", image:"/Im/12121212.png" },
];
